language: elixir
elixir:
  - 1.9.4
otp_release:
  - 22.1.8
env:
  - MIX_ENV=test
sudo: false
before_script:
  - mix format --check-formatted
  - mix compile --warnings-as-errors
  - mix credo --strict
  - mix dialyzer --halt-exit-status
script:
  - mix test
after_script:
  - mix coveralls.travis
cache:
  directories:
  - priv/plts